/**
 * The old site's signature: a 45deg sunset gradient with layered ridges
 * drifting across it. That was a 12KB data-URI SVG generated by carrd; this is
 * three paths built from a repeating height profile.
 *
 * Each ridge is drawn twice end to end and animated by exactly one period, so
 * the second copy lands on where the first started and the loop has no seam.
 */

const STEP = 50
const PERIOD = 8
const WIDTH = STEP * PERIOD * 2

const RIDGES = [
  { heights: [70, 40, 75, 35, 80, 45, 70, 30], fill: '#4a3a5e', duration: '60s' },
  { heights: [92, 58, 96, 52, 90, 62, 96, 56], fill: '#2e2540', duration: '45s' },
  { heights: [118, 88, 122, 82, 120, 90, 124, 92], fill: '#16131a', duration: '30s' },
]

function ridgePath(heights: readonly number[]): string {
  const profile = [...heights, ...heights, heights[0] ?? 0]
  const points = profile.map((y, i) => `${i * STEP},${y}`)
  return `M${points.join(' L')} L${WIDTH},150 L0,150 Z`
}

export default function Backdrop() {
  return (
    <div className="backdrop" aria-hidden="true">
      <svg className="peaks" viewBox="0 0 400 150" preserveAspectRatio="none">
        {RIDGES.map((ridge) => (
          <path
            key={ridge.fill}
            d={ridgePath(ridge.heights)}
            fill={ridge.fill}
            style={{ animationDuration: ridge.duration }}
          />
        ))}
      </svg>
    </div>
  )
}
