#!/usr/bin/env python3
"""Regenerate theme.css from the desktop theme module.

The site has no theme of its own: every colour, font and size comes from
pixeljam.nix so the desktop and the website cannot drift apart. Nix does the
evaluating (the module uses lib and arithmetic), this script only reshapes the
result into CSS custom properties.

    tools/theme_from_nix.py [path/to/pixeljam.nix] > theme.css
"""
import json
import subprocess
import sys
from pathlib import Path

DEFAULT_MODULE = Path.home() / ".config/nixos/themes/pixeljam.nix"

EXPR = """
let
  pkgs = import <nixpkgs> {{}};
  m = import {module} {{ lib = pkgs.lib; inherit pkgs; config = {{}}; }};
  fonts = m.config.stylix.fonts;
in {{
  theme = m.options.theme.default;
  scheme = m.config.stylix.base16Scheme;
  polarity = m.config.stylix.polarity;
  fonts = {{
    mono = fonts.monospace.name;
    sans = fonts.sansSerif.name;
    serif = fonts.serif.name;
    emoji = fonts.emoji.name;
  }};
}}
"""

# Hyprland's blur strength lives outside the theme module (it only says on/off),
# so the pixel radius is the one number chosen here.
BLUR_RADIUS_PX = 12

ANIMATION_SPEEDS = {"very-fast": "80ms", "fast": "120ms", "medium": "180ms", "slow": "300ms"}


def evaluate(module: Path) -> dict:
    out = subprocess.run(
        ["nix", "eval", "--impure", "--json", "--expr", EXPR.format(module=module.resolve())],
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    return json.loads(out)


def render(data: dict, module: Path) -> str:
    theme, scheme, fonts = data["theme"], data["scheme"], data["fonts"]
    lines = [
        f"/* Generated by tools/theme_from_nix.py from {module.name}. Do not edit by hand. */",
        ":root {",
        f"  color-scheme: {data['polarity']};",
    ]
    lines += [f"  --{name}: #{value};" for name, value in sorted(scheme.items())]
    lines += [
        f'  --font-mono: "{fonts["mono"]}", ui-monospace, monospace;',
        f'  --font-sans: "{fonts["sans"]}", system-ui, sans-serif;',
        f'  --font-serif: "{fonts["serif"]}", system-ui, sans-serif;',
        f'  --font-emoji: "{fonts["emoji"]}", "Apple Color Emoji", "Noto Color Emoji", sans-serif;',
        f"  --rounding: {theme['rounding']}px;",
        f"  --bar-height: {theme['bar-height']}px;",
        f"  --gap-in: {theme['gaps-in']}px;",
        f"  --gap-out: {theme['gaps-out']}px;",
        f"  --border: {theme['border-size']}px;",
        f"  --active-opacity: {theme['active-opacity']};",
        f"  --inactive-opacity: {theme['inactive-opacity']};",
        f"  --blur: {BLUR_RADIUS_PX if theme['blur'] else 0}px;",
        f"  --anim: {ANIMATION_SPEEDS[theme['animation-speed']]};",
        "}",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    module = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_MODULE
    sys.stdout.write(render(evaluate(module), module))


if __name__ == "__main__":
    main()
